export const PATH = {
  DEFAULT: "#",
  HOME: "/",
  PAYMENT: "/payment",
  DASHBOARD: "/dashboard",
  LOGIN: "/login",
  FORGET_PASSWORD: "/forget-password",
  RESET_PASSWORD: "/reset-password",
  REGISTER: "/register",
  MY_ACCOUNT: "/user/my-account",
  MY_ADDRESS: "/user/my-address",
  ORDER: "/user/orders",
  NOTIFICATION: "/user/notification",
  VOUCHER: "/user/voucher",
  CATEGORY: "/categories",
  PRODUCT: "/products",
  CREATE_CATEGORY: "/categories/create",
  CREATE_PRODUCT: "/products/create",
};
